### ISSUE TITLE
Error a la hora de migrar la Base de Datos

### ISSUE THREAD

**Issue by edubotdom** [edubotdom/EGC-1819-edubotdom#1]
Cuando se procede a realizar la migración de la base de datos para popularla, se aprecia un error "NameError: name 'path' is not defined"

Se realizan los siguientes pasos.

1. Creamos el usuario de la BBDD
2. Creamos la BBDD
3. Al tratar de migrar la base de datos, para popularla, mediante el comando `python ./manage.py migrate`, se produce un error, con la siguiente traza.

`Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/base.py", line 361, in check
    all_issues = self._run_checks(
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/edmig/egc/lib/python3.8/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/edmig/egc/lib/python3.8/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/edmig/decideCode/EGC-1819-edubotdom/decide/decide/urls.py", line 25, in <module>
    path('admin/', admin.site.urls),
NameError: name 'path' is not defined
`

Por lo que se aprecia en la traza, parece que se trata de un error relacionado con la variable "path", por lo que una posible solución sería revisarla en el archivo "/home/edmig/decideCode/EGC-1819-edubotdom/decide/decide/urls.py".

**Comment by edubotdom** [comment]
Damos por cerrada la incidencia, ya que se ha solucionado el fallo con respecto a la variable path, que se encontraba indebidamente configurada en el fichero urls.py, por lo que ha quedado resuelta.
